apiVersion: v1
kind: Secret
metadata:
  name: racing-game-secrets
  namespace: default
type: Opaque
stringData:
  mongodb-uri: ""  # TODO: Base64 encoded connection string
  jwt-secret: ""   # TODO: Base64 encoded JWT secret
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""  # TODO: Se genera automáticamente