apiVersion: v1
kind: Secret
metadata:
  name: racing-game-secrets
  namespace: default
type: Opaque
stringData:
  jwt-secret: "YjQ0OTc4NzU0MmQyNjk5ODRkOTRjM2I1ZjUyMzJlYTBhMDVkMDljNDRmMWZhMmE4YjU2YjlhZmUyZDc3N2Q1ODc2OWRlMjU0ZjdlNjQ0ODA2Mjg4NjFkZDlmMWY0MmFkMWFhODg3ODI5ODgzMTc0N2Y0YTJhOWEyY2U3NTdhMWE="
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""  # TODO: Se genera automáticamente