name: Trigger auto deployment for racing-game-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/racing-game-backend-AutoDeployTrigger-1f08c36c-4ad3-42ab-91aa-73fd441c2019.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.RACINGGAMEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RACINGGAMEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RACINGGAMEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: racinggamecr.azurecr.io
          registryUsername: ${{ secrets.RACINGGAMEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RACINGGAMEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: racing-game-backend
          resourceGroup: racing-game-rg
          imageToBuild: racinggamecr.azurecr.io/racing-game-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


